### ISSUE TITLE
Too may birds!

### ISSUE THREAD

**Issue by halj78727** [mitchbeebe/new-birdle#3]
I love the new format. So many things to like (bigger photos, more photos, larger text). But PLEASE make a way to limit the scope of birds to a particular geography (e.g. North America). I'm a pretty avid birder, but I have almost no idea about birds all over the world and this isn't the way I want to learn about them. I'm challenged enough with birds of North America. Right now, it is not enjoyable to play. Just frustrating.

**Comment by mitchbeebe** [comment]
Hi halj78727, I appreciate the feedback. The most common requests I heard were more birds, more images, and more games, so those were my top priority in the latest release (as well as migrating my backend to something easier to work with). 

I agree, the new version is quite challenging, so I'm actively working on a region selection. In the meantime, I hope the practice section and hints can help offset the difficulty of the daily game.

**Comment by mitchbeebe** [comment]
Added a regional dropdown, which limits the pool of random daily birds (as well as the suggestions in autocomplete) to only those spotted in that region according to the eBird.org API endpoint listing [species in a region](https://documenter.getpostman.com/view/664302/S1ENwy59#55bd1b26-6951-4a88-943a-d3a8aa1157dd). Stats page also limits to selected region and copied results include region.

**Comment by halj78727** [comment]
Mitch: Thanks for doing this! Though today we seem to have an exception. As
shown in the map, the White Hawk is from South and Central America. It
isn't in the National Geographic Field Guide to Birds of North America. I
did get it on my second guess only by looking for hawks and finding one
that used "white" in the name.

[image: image.png]


Regards,
Hal Jennings
in the Live Music Capital of the World
Austin, TX

**Comment by mitchbeebe** [comment]
Hi Hal, you're right, the White Hawk does appear to be mostly in South/Central America. I'm using the eBird API which lists "species ever seen in a region" (a pretty loose definition), so because the range includes Mexico, it's included in the North American population. Admittedly, it won't be perfect every time, but hopefully more often than not.

**Comment by halj78727** [comment]
Thanks Mitch. I thought it might be something like that. And thanks again
for making this game and updating it to improve it. It is helping me get
better at recognizing and naming birds.


Regards,
Hal Jennings
in the Live Music Capital of the World
Austin, TX
